export const hiragana = [
  [['あ', 'a'], ['い', 'i'], ['う', 'u'], ['え', 'e'], ['お', 'o'], [], ['や ', 'ya'], ['ゆ ', 'yu'], ['よ ', 'yo']],
  [['か', 'ka'], ['き', 'ki'], ['く', 'ku'], ['け', 'ke'], ['こ', 'ko'], [], ['きゃ', 'kya'], ['きゅ', 'kyu'], ['きょ', 'kyo']],
  [['さ', 'sa'], ['し', 'shi'], ['す', 'su'], ['せ', 'se'], ['そ', 'so'], [], ['しゃ', 'sha'], ['しゅ', 'shu'], ['しょ', 'sho']],
  [['た', 'ta'], ['ち', 'chi'], ['つ', 'tsu'], ['て', 'te'], ['と', 'to'], [], ['ちゃ', 'cha'], ['ちゅ', 'chu'], ['ちょ', 'cho']],
  [['な', 'na'], ['に', 'ni'], ['ぬ', 'nu'], ['ね', 'ne'], ['の', 'no'], [], ['にゃ', 'nya'], ['にゅ', 'nyu'], ['にょ', 'nyo']],
  [['は', 'ha'], ['ひ', 'hi'], ['ふ', 'fu'], ['へ', 'he'], ['ほ', 'ho'], [], ['ひゃ', 'hya'], ['ひゅ', 'hyu'], ['ひょ', 'hyo']],
  [['ま', 'ma'], ['み', 'mi'], ['む', 'mu'], ['め', 'me'], ['も', 'mo'], [], ['みゃ', 'mya'], ['みゅ', 'myu'], ['みょ', 'myo']],
  [['ら', 'ra'], ['り', 'ri'], ['る', 'ru'], ['れ', 're'], ['ろ', 'ro'], [], ['りゃ', 'rya'], ['りゅ', 'ryu'], ['りょ', 'ryo']],
  [[]],
  [['が', 'ga'], ['ぎ', 'gi'], ['ぐ', 'gu'], ['げ', 'ge'], ['ご', 'go'], [], ['ぎゃ', 'gya'], ['ぎゅ', 'gyu'], ['ぎょ', 'gyo']],
  [['ざ', 'za'], ['じ', 'ji'], ['ず', 'zu'], ['ぜ', 'ze'], ['ぞ', 'zo'], [], ['じゃ', 'ja'], ['じゅ', 'ju'], ['じょ', 'jo']],
  [['だ', 'da'], ['ぢ', '(ji)'], ['づ', '(zu)'], ['で', 'de'], ['ど', 'do'], [], ['ぢゃ', '(ja)'], ['ぢゅ', '(ju)'], ['ぢょ', '(jo)']],
  [['ば', 'ba'], ['び', 'bi'], ['ぶ', 'bu'], ['べ', 'be'], ['ぼ', 'bo'], [], ['びゃ', 'bya'], ['びゅ', 'byu'], ['びょ', 'byo']],
  [['ぱ', 'pa'], ['ぴ', 'pi'], ['ぷ', 'pu'], ['ぺ', 'pe'], ['ぽ', 'po'], [], ['ぴゃ', 'pya'], ['ぴゅ', 'pyu'], ['ぴょ', 'pyo']],
  [['わ', 'wa'], ['を', 'wo'], ['ん', 'n']]
];

export const katakana = [
  [['ア', 'a'], ['イ', 'i'], ['ウ', 'u'], ['エ', 'e'], ['オ', 'o'], [], ['ヤ ', 'ya'], ['ユ ', 'yu'], ['ヨ ', 'yo']],
  [['カ', 'ka'], ['キ', 'ki'], ['ク', 'ku'], ['ケ', 'ke'], ['コ', 'ko'], [], ['キャ', 'kya'], ['キュ', 'kyu'], ['キョ', 'kyo']],
  [['サ', 'sa'], ['シ', 'shi'], ['ス', 'su'], ['セ', 'se'], ['ソ', 'so'], [], ['シャ', 'sha'], ['シュ', 'shu'], ['ショ', 'sho']],
  [['タ', 'ta'], ['チ', 'chi'], ['ツ', 'tsu'], ['テ', 'te'], ['ト', 'to'], [], ['チャ', 'cha'], ['チュ', 'chu'], ['チョ', 'cho']],
  [['ナ', 'na'], ['ニ', 'ni'], ['ヌ', 'nu'], ['ネ', 'ne'], ['ノ', 'no'], [], ['ニャ', 'nya'], ['ニュ', 'nyu'], ['ニョ', 'nyo']],
  [['ハ', 'ha'], ['ヒ', 'hi'], ['フ', 'fu'], ['ヘ', 'he'], ['ホ', 'ho'], [], ['ヒャ', 'hya'], ['ヒュ', 'hyu'], ['ヒョ', 'hyo']],
  [['マ', 'ma'], ['ミ', 'mi'], ['ム', 'mu'], ['メ', 'me'], ['モ', 'mo'], [], ['ミャ', 'mya'], ['ミュ', 'myu'], ['ミョ', 'myo']],
  [['ラ', 'ra'], ['リ', 'ri'], ['ル', 'ru'], ['レ', 're'], ['ロ', 'ro'], [], ['リャ', 'rya'], ['リュ', 'ryu'], ['リョ', 'ryo']],
  [[]],
  [['ガ', 'ga'], ['ギ', 'gi'], ['グ', 'gu'], ['ゲ', 'ge'], ['ゴ', 'go'], [], ['ギャ', 'gya'], ['ギュ', 'gyu'], ['ギョ', 'gyo']],
  [['ザ', 'za'], ['ジ', 'ji'], ['ズ', 'zu'], ['ゼ', 'ze'], ['ゾ', 'zo'], [], ['ジャ', 'ja'], ['ジュ', 'ju'], ['ジョ', 'jo']],
  [['ダ', 'da'], ['ヂ', '(ji)'], ['ヅ', '(zu)'], ['デ', 'de'], ['ド', 'do'], [], ['ヂャ', '(ja)'], ['ヂュ', '(ju)'], ['ヂョ', '(jo)']],
  [['バ', 'ba'], ['ビ', 'bi'], ['ブ', 'bu'], ['ベ', 'be'], ['ボ', 'bo'], [], ['ビャ', 'bya'], ['ビュ', 'byu'], ['ビョ', 'byo']],
  [['パ', 'pa'], ['ピ', 'pi'], ['プ', 'pu'], ['ペ', 'pe'], ['ポ', 'po'], [], ['ピャ', 'pya'], ['ピュ', 'pyu'], ['ピョ', 'pyo']],
  [['ワ', 'wa'], ['ヲ', 'wo'], ['ン', 'n']]
];

 //  N5
 //  Znak, Tłuaczenie, OnReading, KunReading
export const kanji = [
  [['一', 'Jeden', 'Ichi / Itsu', 'Hito / Hito.u'],
    ['二', 'Dwa', 'Ni / Ji', 'Futa / Futa.tsu'],
    ['三', 'Trzy', 'San', 'Mi / Mit.tsu'],
    ['四', 'Cztery', 'Shi', 'Yo / Yot.tsu'],
    ['五', 'Pięć', 'Go', 'Itsu'], [],
    ['六', 'Sześć', 'Roku / Riki', 'Mu / Mui / Mut.tsu'],
    ['七', 'Siedem', 'Shichi', 'Nana / Nano / Nana.tsu'],
    ['八', 'Osiem', 'Hachi', 'Ya / Ya.tsu']],
  [['九', 'Dziewięć', 'Kyuu / Ku', 'Kokono / Kokono.tsu'],
    ['十', 'Dziesięć', 'Too / To', 'Juu / Ji'],
    ['百', 'Sto', 'Hyaku / Byaku', ''],
    ['千', 'Tysiąc', 'Sen', 'Chi'],
    ['万', 'Dziesięć tysięcy', 'Man / Ban', ''], [],
    ['水', 'Woda', 'Sui', 'Mizu'],
    ['火', 'Ogień', 'Ka', 'Hi / Ho / Bi'],
    ['木', 'Drzewo / Drewno', 'Boku / Moku', 'Ki / Ko']],
  [['天', 'Niebo', 'Ten', 'Ame / Ama / Amatsu'],
    ['土', 'Ziemia', 'Do / To', 'Tsuchi'],
    ['北', 'Północ', 'Hoku', 'Kita'],
    ['東', 'Wschód', 'Tou', 'Higashi'],
    ['西', 'Zachód', 'Sei / Sai / Su', 'Nishi'], [],
    ['南', 'Południe', 'Nan', 'Minami'],
    ['左', 'Lewo', 'Sa / Sha', 'Hidari'],
    ['右', 'Prawo', 'U / Yuu', 'Migi']],
  [['日', 'Dzień / Słońce', 'Nichi / Jitsu', 'Hi / Bi / Ka'],
    ['月', 'Miesiąc / Księżyc', 'Getsu / Gatsu', 'Tsuki'],
    ['花', 'Kwiat', 'Ka / Ke', 'Hana'],
    ['魚', 'Ryba', 'Gyo', 'Uo / Sakana'],
    ['空', 'Niebo / Pustka / Głód', 'Kuu', 'Sora / A.Ki / Kara / Su.Ku / Su.Kasu'], [],
    ['山', 'Góra', 'San / Sen', 'Yama'],
    ['川', 'Rzeka', 'Sen', 'Kawa'],
    ['雨', 'Deszcz', 'U', 'Ame / Ama']],
  [['本', 'Książka / Źródło', 'Hon', 'Moto'],
    ['目', 'Oko', 'Moku / Boku', 'Me / Ma'],
    ['口', 'Usta', 'Kou / Ku', 'Kuchi'],
    ['耳', 'Ucho', 'Ji', 'Mimi'],
    ['手', 'Ręka', 'Shu / Zu', 'Te'], [],
    ['足', 'Stopa / Noga', 'Soku', 'Ashi', 'Ta.ru / Ta.su'],
    ['人', 'Człowiek', 'Nin / Jin', 'Hito'],
    ['母', 'Mama', 'Bo', 'Haha / Mo']],
  [['父', 'Tata', 'Fu', 'Chichi'],
    ['女', 'Kobieta', 'Jo / Nyo / Nyou', 'Onna / Me'],
    ['男', 'Mężczyzna', 'Dan / Nan', 'Otoko / O'],
    ['子', 'Dziecko', 'Shi / Su / Tsu', 'Ko'],
    ['小', 'Mały', 'Shou', 'Chii.sai / Ko / O / Sa'], [],
    ['中', 'Wewnątrz / Pomiędzy', 'Chuu', 'Naka'],
    ['大', 'Duży', 'Tai / Dai', 'Oo / .ki / .i / .ni'],
    ['上', 'Nad', 'Jou / Shou', 'Ue / Kami / A.geru / A.garu']],
  [['下', 'Poniżej', 'Ka / Ge', 'Shita / Sa.geru / O.rosu / Ku.daru'],
    ['何', 'Co / Ile / Który', 'Ka', 'Nani'],
    ['行', 'Iść', 'Kou / Gyou / An', 'I.ku / Yu.ku', 'Okona.u'],
    ['見', 'Oglądać / Pokazywać', 'Ken', 'Mi.ru / .eru / .seru'],
    ['言', 'Słowo', 'Gen / Gon', 'I.u / Gen / Koto'], [],
    ['語', 'Język', 'Go', 'Kara.ru / .rau'],
    ['食', 'Jedzenie / Jeść', 'Shoku / Jiki', 'Ta.beru / Ku.u / .rau'],
    ['飲', 'Pić / Palić', 'In', 'No.mu']],
  [['会', 'Spotykać / Impreza', 'Kai / E', 'A.u'],
    ['学', 'Uczyć się', 'Gaku', 'Mana.bu'],
    ['休', 'Odpoczywać', 'Kyuu', 'Yasu.mu / .meru / maru'],
    ['買', 'Kupować', 'Bai', 'Ka.u'],
    ['聞', 'Słuchać', 'Bun / Mun', 'Ki.ku / .koeru'], [],
    ['来', 'Przychodzić', 'Rai', 'Ku.ru / Kita.ru / .su'],
    ['立', 'Stać / Wznośić', 'Ritsu / Ryuu', 'Ta.tsu / .teru / .chi'],
    ['生', 'Życie / Narodziny', 'Sei / Shou', 'I.kuru / U.mareru / .mu']],
  [[]],
  [['話', 'Konwersacja / Mowa', 'Wa', 'Hanashi / Hana.su'],
    ['出', 'Wyjście / Wychodzić', 'Shutsu', 'De.ru / Da.su'],
    ['読', 'Czytać', 'Doku / Toku', 'Yo.mu'],
    ['入', 'Wchodzić', 'Nyuu / Ju', 'Hai.ru / I.ru / .re / .reru'],
    ['書', 'Pisać', 'Sho', 'Ka.ku'], [],
    ['後', 'Później', 'Go / Kou', 'Ato / Okure.ru / Nochi'],
    ['古', 'Stare / Używane', 'Ko', 'Furi.i'],
    ['高', 'Duże / Drogie', 'Kou', 'Taka / .i / .meru / .maru']],
  [['安', 'Bezpieczne / Tanie', 'An', 'Yasu.i'],
    ['多', 'Wiele', 'Ta', 'Oo.i'],
    ['新', 'Nowy', 'Shin', 'Atara.shii / Ara.ta'],
    ['少', 'Niewiele', 'Shou', 'Suko.shi / Suku.nai'],
    ['長', 'Długi / Lider', 'Chou', 'Naga.i / Osa'], [],
    ['白', 'Biały', 'Haku / Byaku', 'Shira / .i'],
    ['分', 'Część / Minuta / Dzielić', 'Fun / Bu', 'Wa.keru / .karu / .kareru'],
    ['時', 'Godzina / Czas', 'Ji', 'Toki / Doki']],
  [['間', 'Interwał / Okres czasu', 'Kan / Ken', 'Ai / Aida / Ma'],
    ['週', 'Tydzień', 'Shuu', 'Hito'],
    ['年', 'Rok', 'Nen', 'Toshi'],
    ['今', 'Nowy', 'Kon / Kin', 'Ima'],
    ['先', 'Wcześniej', 'Sen', 'Saki / Ma.zu'], [],
    ['前', 'Przed', 'Zen', 'Mae'],
    ['午', 'Południe', 'Go', ''],
    ['半', 'Połowa', 'Han', 'Naka.ba']],
  [['店', 'Sklep', 'Ten', 'Mise / Tana'],
    ['外', 'Inny / Obcy / Obcokrajowiec', 'Gai / Ge', 'Soto / Hoka'],
    ['電', 'Elektryczność', 'Den', ''],
    ['道', 'Droga / Moralność', 'Dou', 'Michi'],
    ['毎', 'Każdy', 'Mai', 'Doto'], [],
    ['友', 'Przyjaciel', 'Yuu', 'Tomo'],
    ['名', 'Imię', 'Mei / Myou', 'Na'],
    ['金', 'Złoto / Metal / Pieniądze', 'Kin / Kon', 'Kane / Kana']],
  [['円', 'Yen / Okrągły', 'En', 'Maru / .i'],
    ['車', 'Samochód / Koło', 'Sha', 'Kuruma'],
    ['駅', 'Stacja', 'Eki', ''],
    ['気', 'Dusza / Umysł', 'Ki / Kei', ''],
    ['国', 'Kraj', 'Koku', 'Kuni'], [],
    ['社', 'Świątyna / Firma', 'Sha', 'Yashiro'],
    ['校', 'Szkoła', 'Kou', ''],
    ['肉', 'Mięso / Ciało', 'Niku', 'Shishi']]
];
